modLoader = "javafml"
loaderVersion = "[34,)"
license = "GNU GPLv3"
[[mods]]
modId = "mobfarmutilities"
version = "${version}"
displayName = "Mob Farm Helpers"
issueTrackerURL = "https://github.com/yzl210/MobFarmUtilities/issues"
authors = "6LeoMC"
description = '''
Add some useful mob farm utilities
'''

[[dependencies.mobfarmutilities]]
modId = "architectury"
mandatory = true
versionRange = "[1.8.130,)"
ordering = "AFTER"
side = "BOTH"